### ISSUE TITLE
Invalid username or password even with correct credentials

### ISSUE THREAD

**Issue by Roopaish** [ayyshim/esewa_pnp#48]
I tried to sign in with mobile/email and MPIN but it says 'Invalid username or password' even though it's working on the main app.  
  
I used the provided clientId and secretkey mentioned in the Readme.

**Comment by ayyshim** [comment]
If you are using the client ID and secret key mentioned in the README documentation then you need to try logging in with test credentials that are provided by esewa.

Mobile/Email: 9806800001/2/3/4
Password: Nepal@123

Closing this issue with this comment because this issue does not relate with plugin itself.
